apiVersion: v1
kind: Namespace
metadata:
  name: openspeedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openspeedtest
  name: openspeedtest
spec:
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata: 
      labels:
        app: openspeedtest
    spec:
      containers:
      - name: openspeedtest
        image: openspeedtest/latest:latest
        resources:
          limits:
            memory: "500Mi" 
            cpu: "1000m"
        ports:
        - containerPort: 3000
        - containerPort: 3001
---
kind: Service
apiVersion: v1
metadata:
  namespace: openspeedtest
  name: openspeedtest
spec:
  selector:
    app: openspeedtest
  type: NodePort
  ports:
  - name: web
    port: 3000
    targetPort: 3000
  - name: speedtest
    port: 3001
    targetPort: 3001
